# ============================
#        Builder
# ============================
FROM ubuntu:18.04 as builder

# Install build dependencies
RUN apt-get update && \
    apt-get install -y build-essential autoconf automake libtool git bison flex wget

# Create directories for scripts, jq sources and output.
RUN mkdir /app /jq /out

COPY checkout.sh /app
COPY build-linux.sh /app

# Checkout jq commit.
ARG JQ_GIT_SHA
RUN /app/checkout.sh $JQ_GIT_SHA /jq

# Build libjq and jq binary, create checksum file.
RUN /app/build-linux.sh /jq /out

# ============================
#        Final image
# ============================
FROM scratch
COPY --from=builder /out/ /
ENTRYPOINT /bin/jq
